### ISSUE TITLE
Investigate possible locations in IO kernel stack

### ISSUE THREAD

**Issue by w-michal** [googleinterns/scsi2nvme#38]
Reference - [Linux storage stack diagram
](https://www.thomas-krenn.com/en/wiki/Linux_Storage_Stack_Diagram)
General idea of the module “location”:
![Linux-storage-stack-diagram_v4 10](https://user-images.githubusercontent.com/2938327/83211000-d3039f00-a110-11ea-8f2f-39f019e5477a.jpg)
To investigate:
- At what layer of SCSI we want to intercept? We probably want to either mimic a “low level driver” and expose a ‘fake’ SCSI driver  . 
- How can we easily communicate with NVMe drivers?
- Do we have to communicate with the block layer? My guess is “no” but we have to double check. 

Note: There is a chance that some SCSI definitions are already in Linux source - the reason why we have our own redefined is that our module should be reusable in different places, not only kernel itself.

**Comment by basimsahaf** [comment]
I wrote a design doc to suggest an appropriate location for our translation engine in the linux kernel. You can find it here: https://docs.google.com/document/d/1oIBSRtmAC7Pkx6esm72y28gvOOD7JflM0jNwDL-_EV0/edit?usp=sharing
