### ISSUE TITLE
Nvme Transfer mode

### ISSUE THREAD

**Issue by eyhhuang** [googleinterns/scsi2nvme#49]
“Transfer mode” (prp vs SGL with some extra options, part of read or write command)

**Comment by harloff-g** [comment]
Does #48 close this?
https://github.com/googleinterns/scsi2nvme/pull/48/files#diff-341c4b7d4b82b80805d1f0e1ac7f64a0R263

**Comment by eyhhuang** [comment]
I think you are right. I looked at the specifications for the read and write commands and they just specify which fields are used in the read/write. I don't think there are any structs to import/implement.
